/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Route1RouteImport } from './routes/route1'
import { Route as Route2RouteImport } from './routes/route2'

const Route1Route = Route1RouteImport.update({
  id: '/route1',
  path: '/route1',
  getParentRoute: () => rootRouteImport,
} as any)
const Route2Route = Route2RouteImport.update({
  id: '/route2',
  path: '/route2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/route1': typeof Route1Route
  '/route2': typeof Route2Route
}
export interface FileRoutesByTo {
  '/route1': typeof Route1Route
  '/route2': typeof Route2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/route1': typeof Route1Route
  '/route2': typeof Route2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/route1' | '/route2'
  fileRoutesByTo: FileRoutesByTo
  to: '/route1' | '/route2'
  id: '__root__' | '/route1' | '/route2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Route1Route: typeof Route1Route
  Route2Route: typeof Route2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/route1': {
      id: '/route1'
      path: '/route1'
      fullPath: '/route1'
      preLoaderRoute: typeof Route1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route2': {
      id: '/route2'
      path: '/route2'
      fullPath: '/route2'
      preLoaderRoute: typeof Route2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Route1Route: Route1Route,
  Route2Route: Route2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
